{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "630d2343-7e62-4eda-9301-ba3124e1d634",
   "metadata": {},
   "outputs": [],
   "source": [
    "import streamlit as st\n",
    "import pandas as pd\n",
    "import numpy as np\n",
    "import joblib\n",
    "import matplotlib.pyplot as plt\n",
    "import seaborn as sns\n",
    "\n",
    "# --- LOAD MODEL ---\n",
    "# This block tries to load the model. If it fails, it stops the app gracefully.\n",
    "try:\n",
    "    model = joblib.load('diabetes_model.pkl')\n",
    "    scaler = joblib.load('scaler.pkl')\n",
    "except FileNotFoundError:\n",
    "    st.error(\"⚠️ Error: Model files not found!\")\n",
    "    st.warning(\"Please make sure 'diabetes_model.pkl' and 'scaler.pkl' are in the same folder as this app.py file.\")\n",
    "    st.stop()\n",
    "\n",
    "# --- APP CONFIGURATION ---\n",
    "st.set_page_config(page_title=\"Diabetes Risk AI\", page_icon=\"🩺\", layout=\"wide\")\n",
    "\n",
    "# Custom CSS\n",
    "st.markdown(\"\"\"\n",
    "    <style>\n",
    "    .big-font { font-size:30px !important; font-weight: bold; color: #2E86C1; }\n",
    "    .stButton>button { background-color: #2E86C1; color: white; border-radius: 10px; }\n",
    "    </style>\n",
    "    \"\"\", unsafe_allow_html=True)\n",
    "\n",
    "# --- HEADER ---\n",
    "st.markdown('<p class=\"big-font\">🩺 Intelligent Diabetes Intervention System</p>', unsafe_allow_html=True)\n",
    "st.markdown(\"An industrial-grade AI system for early detection.\")\n",
    "st.divider()\n",
    "\n",
    "# --- SIDEBAR INPUTS ---\n",
    "st.sidebar.header(\"Patient Vitals\")\n",
    "def user_input_features():\n",
    "    pregnancies = st.sidebar.slider('Pregnancies', 0, 17, 3)\n",
    "    glucose = st.sidebar.slider('Glucose', 0, 200, 117)\n",
    "    bp = st.sidebar.slider('Blood Pressure', 0, 122, 72)\n",
    "    skin = st.sidebar.slider('Skin Thickness', 0, 99, 23)\n",
    "    insulin = st.sidebar.slider('Insulin', 0, 846, 30)\n",
    "    bmi = st.sidebar.slider('BMI', 0.0, 67.1, 32.0)\n",
    "    dpf = st.sidebar.slider('Diabetes Pedigree Function', 0.0, 2.4, 0.37)\n",
    "    age = st.sidebar.slider('Age', 21, 81, 29)\n",
    "    \n",
    "    return pd.DataFrame({\n",
    "        'Pregnancies': [pregnancies], 'Glucose': [glucose], 'BloodPressure': [bp],\n",
    "        'SkinThickness': [skin], 'Insulin': [insulin], 'BMI': [bmi],\n",
    "        'DiabetesPedigreeFunction': [dpf], 'Age': [age]\n",
    "    })\n",
    "\n",
    "input_df = user_input_features()\n",
    "\n",
    "# --- MAIN PAGE ---\n",
    "col1, col2 = st.columns([2, 1])\n",
    "\n",
    "with col1:\n",
    "    st.subheader(\"Patient Data\")\n",
    "    st.dataframe(input_df)\n",
    "\n",
    "    if st.button('Analyze Risk Profile'):\n",
    "        # Prediction\n",
    "        input_scaled = scaler.transform(input_df)\n",
    "        prediction_prob = model.predict_proba(input_scaled)\n",
    "        risk_score = prediction_prob[0][1]\n",
    "        \n",
    "        # Display\n",
    "        st.subheader(\"Results\")\n",
    "        if risk_score < 0.3:\n",
    "            st.success(f\"Low Risk: {risk_score:.1%}\")\n",
    "        elif risk_score < 0.7:\n",
    "            st.warning(f\"Moderate Risk: {risk_score:.1%}\")\n",
    "        else:\n",
    "            st.error(f\"High Risk: {risk_score:.1%}\")\n",
    "\n",
    "        # Recommendations\n",
    "        st.divider()\n",
    "        st.subheader(\"AI Recommendations\")\n",
    "        if input_df['Glucose'].values[0] > 140:\n",
    "             st.info(\"• Glucose is high. Consider HbA1c test.\")\n",
    "        if input_df['BMI'].values[0] > 30:\n",
    "             st.info(\"• Patient is in the obese range. Lowering BMI is the most effective intervention.\")\n",
    "        if input_df['Age'].values[0] > 50:\n",
    "             st.info(\"• Age is a risk factor. Regular screening recommended.\")\n",
    "\n",
    "with col2:\n",
    "    st.subheader(\"Visual Comparison\")\n",
    "    # Simple chart\n",
    "    fig, ax = plt.subplots()\n",
    "    metrics = ['Glucose', 'BP', 'BMI']\n",
    "    avgs = [100, 70, 22]\n",
    "    user_vals = [input_df['Glucose'][0], input_df['BloodPressure'][0], input_df['BMI'][0]]\n",
    "    \n",
    "    x = np.arange(len(metrics))\n",
    "    ax.bar(x - 0.17, avgs, 0.35, label='Healthy Avg', color='green')\n",
    "    ax.bar(x + 0.17, user_vals, 0.35, label='Patient', color='blue')\n",
    "    ax.set_xticks(x)\n",
    "    ax.set_xticklabels(metrics)\n",
    "    ax.legend()\n",
    "    st.pyplot(fig)"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.13.5"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
