{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 1,
   "id": "a518a165-1628-4dc1-8a5d-640f3535b4ca",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Collecting catboost\n",
      "  Downloading catboost-1.2.8-cp313-cp313-macosx_11_0_universal2.whl.metadata (1.4 kB)\n",
      "Collecting graphviz (from catboost)\n",
      "  Downloading graphviz-0.21-py3-none-any.whl.metadata (12 kB)\n",
      "Requirement already satisfied: matplotlib in /opt/miniconda3/lib/python3.13/site-packages (from catboost) (3.10.8)\n",
      "Requirement already satisfied: numpy<3.0,>=1.16.0 in /opt/miniconda3/lib/python3.13/site-packages (from catboost) (2.4.1)\n",
      "Requirement already satisfied: pandas>=0.24 in /opt/miniconda3/lib/python3.13/site-packages (from catboost) (2.3.3)\n",
      "Requirement already satisfied: scipy in /opt/miniconda3/lib/python3.13/site-packages (from catboost) (1.17.0)\n",
      "Requirement already satisfied: plotly in /opt/miniconda3/lib/python3.13/site-packages (from catboost) (6.5.2)\n",
      "Requirement already satisfied: six in /opt/miniconda3/lib/python3.13/site-packages (from catboost) (1.17.0)\n",
      "Requirement already satisfied: python-dateutil>=2.8.2 in /opt/miniconda3/lib/python3.13/site-packages (from pandas>=0.24->catboost) (2.9.0.post0)\n",
      "Requirement already satisfied: pytz>=2020.1 in /opt/miniconda3/lib/python3.13/site-packages (from pandas>=0.24->catboost) (2025.2)\n",
      "Requirement already satisfied: tzdata>=2022.7 in /opt/miniconda3/lib/python3.13/site-packages (from pandas>=0.24->catboost) (2025.3)\n",
      "Requirement already satisfied: contourpy>=1.0.1 in /opt/miniconda3/lib/python3.13/site-packages (from matplotlib->catboost) (1.3.3)\n",
      "Requirement already satisfied: cycler>=0.10 in /opt/miniconda3/lib/python3.13/site-packages (from matplotlib->catboost) (0.12.1)\n",
      "Requirement already satisfied: fonttools>=4.22.0 in /opt/miniconda3/lib/python3.13/site-packages (from matplotlib->catboost) (4.61.1)\n",
      "Requirement already satisfied: kiwisolver>=1.3.1 in /opt/miniconda3/lib/python3.13/site-packages (from matplotlib->catboost) (1.4.9)\n",
      "Requirement already satisfied: packaging>=20.0 in /opt/miniconda3/lib/python3.13/site-packages (from matplotlib->catboost) (25.0)\n",
      "Requirement already satisfied: pillow>=8 in /opt/miniconda3/lib/python3.13/site-packages (from matplotlib->catboost) (12.1.0)\n",
      "Requirement already satisfied: pyparsing>=3 in /opt/miniconda3/lib/python3.13/site-packages (from matplotlib->catboost) (3.3.1)\n",
      "Requirement already satisfied: narwhals>=1.15.1 in /opt/miniconda3/lib/python3.13/site-packages (from plotly->catboost) (2.16.0)\n",
      "Downloading catboost-1.2.8-cp313-cp313-macosx_11_0_universal2.whl (27.8 MB)\n",
      "\u001b[2K   \u001b[90m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\u001b[0m \u001b[32m27.8/27.8 MB\u001b[0m \u001b[31m8.7 MB/s\u001b[0m eta \u001b[36m0:00:00\u001b[0m00:01\u001b[0m00:01\u001b[0m\n",
      "\u001b[?25hDownloading graphviz-0.21-py3-none-any.whl (47 kB)\n",
      "Installing collected packages: graphviz, catboost\n",
      "\u001b[2K   \u001b[90m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\u001b[0m \u001b[32m2/2\u001b[0m [catboost]1/2\u001b[0m [catboost]\n",
      "\u001b[1A\u001b[2KSuccessfully installed catboost-1.2.8 graphviz-0.21\n",
      "Note: you may need to restart the kernel to use updated packages.\n"
     ]
    }
   ],
   "source": [
    "pip install catboost"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 3,
   "id": "44f2ba33-7826-4d03-b41c-d11cc4506ca1",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "⏳ Loading data...\n",
      "🧹 Removing physical impossibilities...\n",
      "⚖️  Balancing dataset...\n",
      "🏗️  Building Stacking Ensemble...\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "/opt/miniconda3/lib/python3.13/site-packages/xgboost/training.py:199: UserWarning: [21:38:57] WARNING: /Users/runner/work/xgboost/xgboost/src/learner.cc:790: \n",
      "Parameters: { \"use_label_encoder\" } are not used.\n",
      "\n",
      "  bst.update(dtrain, iteration=i, fobj=obj)\n",
      "/opt/miniconda3/lib/python3.13/site-packages/xgboost/training.py:199: UserWarning: [21:39:00] WARNING: /Users/runner/work/xgboost/xgboost/src/learner.cc:790: \n",
      "Parameters: { \"use_label_encoder\" } are not used.\n",
      "\n",
      "  bst.update(dtrain, iteration=i, fobj=obj)\n",
      "/opt/miniconda3/lib/python3.13/site-packages/xgboost/training.py:199: UserWarning: [21:39:00] WARNING: /Users/runner/work/xgboost/xgboost/src/learner.cc:790: \n",
      "Parameters: { \"use_label_encoder\" } are not used.\n",
      "\n",
      "  bst.update(dtrain, iteration=i, fobj=obj)\n",
      "/opt/miniconda3/lib/python3.13/site-packages/xgboost/training.py:199: UserWarning: [21:39:01] WARNING: /Users/runner/work/xgboost/xgboost/src/learner.cc:790: \n",
      "Parameters: { \"use_label_encoder\" } are not used.\n",
      "\n",
      "  bst.update(dtrain, iteration=i, fobj=obj)\n",
      "/opt/miniconda3/lib/python3.13/site-packages/xgboost/training.py:199: UserWarning: [21:39:01] WARNING: /Users/runner/work/xgboost/xgboost/src/learner.cc:790: \n",
      "Parameters: { \"use_label_encoder\" } are not used.\n",
      "\n",
      "  bst.update(dtrain, iteration=i, fobj=obj)\n",
      "/opt/miniconda3/lib/python3.13/site-packages/xgboost/training.py:199: UserWarning: [21:39:01] WARNING: /Users/runner/work/xgboost/xgboost/src/learner.cc:790: \n",
      "Parameters: { \"use_label_encoder\" } are not used.\n",
      "\n",
      "  bst.update(dtrain, iteration=i, fobj=obj)\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "\n",
      "==============================\n",
      "🚀 FINAL ACCURACY: 77.27%\n",
      "==============================\n",
      "\n",
      "Classification Report:\n",
      "               precision    recall  f1-score   support\n",
      "\n",
      "           0       0.79      0.75      0.77       100\n",
      "           1       0.76      0.80      0.78        98\n",
      "\n",
      "    accuracy                           0.77       198\n",
      "   macro avg       0.77      0.77      0.77       198\n",
      "weighted avg       0.77      0.77      0.77       198\n",
      "\n",
      "✅ Advanced Model Saved!\n"
     ]
    }
   ],
   "source": [
    "import pandas as pd\n",
    "import numpy as np\n",
    "import joblib\n",
    "from sklearn.model_selection import train_test_split, StratifiedKFold, cross_val_score\n",
    "from sklearn.preprocessing import RobustScaler\n",
    "from sklearn.impute import KNNImputer\n",
    "from sklearn.ensemble import RandomForestClassifier, StackingClassifier, GradientBoostingClassifier\n",
    "from sklearn.linear_model import LogisticRegression\n",
    "from xgboost import XGBClassifier\n",
    "from sklearn.metrics import accuracy_score, classification_report\n",
    "from imblearn.over_sampling import SMOTE\n",
    "\n",
    "# 1. LOAD DATA\n",
    "print(\"⏳ Loading data...\")\n",
    "df = pd.read_csv('diabetes.csv')\n",
    "\n",
    "# 2. OUTLIER REMOVAL (The \"Cleanup Crew\")\n",
    "print(\"🧹 Removing physical impossibilities...\")\n",
    "df = df[df['Insulin'] < 600] \n",
    "df = df[df['SkinThickness'] < 80]\n",
    "df = df[df['Glucose'] > 40] \n",
    "\n",
    "# 3. ADVANCED IMPUTATION (KNN)\n",
    "cols_missing = ['Glucose', 'BloodPressure', 'SkinThickness', 'Insulin', 'BMI']\n",
    "df[cols_missing] = df[cols_missing].replace(0, np.nan)\n",
    "imputer = KNNImputer(n_neighbors=5)\n",
    "df[cols_missing] = imputer.fit_transform(df[cols_missing])\n",
    "\n",
    "# 4. FEATURE ENGINEERING\n",
    "df['Insulin_Glucose_Ratio'] = df['Insulin'] / df['Glucose']\n",
    "df.replace([np.inf, -np.inf], 0, inplace=True)\n",
    "\n",
    "def categorize_bmi(bmi):\n",
    "    if bmi < 25: return 0\n",
    "    elif bmi < 30: return 1\n",
    "    else: return 2\n",
    "df['BMI_Class'] = df['BMI'].apply(categorize_bmi)\n",
    "df['Age_Glucose'] = df['Age'] * df['Glucose']\n",
    "\n",
    "# 5. SPLIT DATA\n",
    "X = df.drop('Outcome', axis=1)\n",
    "y = df['Outcome']\n",
    "\n",
    "# 6. SMOTE (Balancing)\n",
    "print(\"⚖️  Balancing dataset...\")\n",
    "smote = SMOTE(random_state=42)\n",
    "X_balanced, y_balanced = smote.fit_resample(X, y)\n",
    "\n",
    "X_train, X_test, y_train, y_test = train_test_split(X_balanced, y_balanced, test_size=0.2, random_state=42)\n",
    "\n",
    "# 7. ROBUST SCALING\n",
    "scaler = RobustScaler()\n",
    "X_train_scaled = scaler.fit_transform(X_train)\n",
    "X_test_scaled = scaler.transform(X_test)\n",
    "\n",
    "# 8. DEFINE STRONG MODELS\n",
    "# Replaced CatBoost with GradientBoostingClassifier to fix the error\n",
    "rf = RandomForestClassifier(n_estimators=200, max_depth=10, min_samples_split=5, random_state=42)\n",
    "xgb = XGBClassifier(eval_metric='logloss', learning_rate=0.05, n_estimators=200, max_depth=5, use_label_encoder=False, random_state=42)\n",
    "gb = GradientBoostingClassifier(n_estimators=200, learning_rate=0.05, max_depth=5, random_state=42)\n",
    "\n",
    "# 9. STACKING (The \"Kaggle Winner\" Technique)\n",
    "print(\"🏗️  Building Stacking Ensemble...\")\n",
    "stacking_model = StackingClassifier(\n",
    "    estimators=[\n",
    "        ('rf', rf),\n",
    "        ('xgb', xgb),\n",
    "        ('gb', gb) # Replaced 'cat' with 'gb'\n",
    "    ],\n",
    "    final_estimator=LogisticRegression(),\n",
    "    cv=5\n",
    ")\n",
    "\n",
    "# 10. TRAIN\n",
    "stacking_model.fit(X_train_scaled, y_train)\n",
    "\n",
    "# 11. EVALUATE\n",
    "y_pred = stacking_model.predict(X_test_scaled)\n",
    "acc = accuracy_score(y_test, y_pred)\n",
    "\n",
    "print(\"\\n\" + \"=\"*30)\n",
    "print(f\"🚀 FINAL ACCURACY: {acc:.2%}\")\n",
    "print(\"=\"*30)\n",
    "print(\"\\nClassification Report:\\n\", classification_report(y_test, y_pred))\n",
    "\n",
    "# 12. SAVE\n",
    "joblib.dump(stacking_model, 'diabetes_model.pkl')\n",
    "joblib.dump(scaler, 'scaler.pkl')\n",
    "print(\"✅ Advanced Model Saved!\")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "3e2c9359-ce8e-43ee-bc12-1e4b3a03d815",
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.13.5"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
